services:
  glpi:
    image: "glpi/glpi:10.0.20"
#   restart: unless-stopped
    volumes:
      - "./storage/glpi/files:/var/glpi/files:rw"
      - "./storage/glpi/config:/var/glpi/config:rw"
      - "./storage/marketplace:/var/glpi/marketplace:rw"
      - "./glpi/entrypoint.sh:/entrypoint.sh"
    entrypoint: ["/entrypoint.sh"]
    env_file: .env
    container_name: glpi-docker-10
    user: "33:33"
    networks:
      - default
      - proxy
    labels:
      # --- Configuração do Traefik ---
      - "traefik.enable=true"
      # Define que este serviço pertence à rede do proxy para o Traefik
      - "traefik.docker.network=proxy"
      # --- Roteador HTTP ---
      # Cria um roteador chamado 'glpi' que responde no domínio abaixo
      - "traefik.http.routers.glpi.rule=Host(`glpi10.wpacloud.tech`)"
      # Associa este roteador ao entrypoint seguro (HTTPS)
      - "traefik.http.routers.glpi.entrypoints=websecure"
      # HABILITA o TLS para este roteador (aqui está a correção principal)
      - "traefik.http.routers.glpi.tls=true"

      # --- Serviço ---
      # Define qual porta interna do container o Traefik deve usar
      - "traefik.http.services.glpi.loadbalancer.server.port=80"

  db:
    image: "mariadb:10.11"
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=glpi
      - MARIADB_USER=glpi
      - MARIADB_PASSWORD=glpi
      - TZ=${TZ}
    volumes:
      - "./storage/mysql:/var/lib/mysql"
      - "./init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u${GLPI_DB_USER} -p${GLPI_DB_PASSWORD} ${GLPI_DB_NAME} -e 'SELECT 1' || exit 1"]
      interval: 10s
    container_name: glpi-docker-db-10

networks:
  proxy:
    name: proxy
    external: true
  default:
    name: glpi_net # rede interna
