<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvVg0vM\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvVg0vM/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerZvVg0vM.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerZvVg0vM\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerZvVg0vM\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'ZvVg0vM',
    'container.build_id' => 'a8984962',
    'container.build_time' => 1757557982,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvVg0vM');
